### ISSUE TITLE
your bolg background color? 

### ISSUE THREAD

**Issue by linghutf** [luuman/hexo-theme-spfk#1]
why I use you theme in my blog,but the backgroud color is white?
I think your blog background is pretty good?Could you give me the css sample?Tks!

**Comment by luuman** [comment]
不好意思，我最近都抽空在修改，觉得不够完善，就没有更新。现在可以了！I am sorry, I have been taking the time to modify, feel not perfect, there is no update. Can now!

**Comment by iamcco** [comment]
@luuman 主题配色还是白色

**Comment by iamcco** [comment]
@luuman 知道原因了，README.md文件的的git地址不是本repo

**Comment by ebnbin** [comment]
yes! @linghutf It should be "git clone https://github.com/luuman/hexo-theme-spfk.git themes/spfk".

**Comment by linghutf** [comment]
I have seen the lastest demo,before it,I had implement my color theme,but there is some problem,it just show not good white color when you try to use **single line code** like `npm list -g``
