### ISSUE TITLE
多说评论样式文件替换

### ISSUE THREAD

**Issue by cbfg5210** [luuman/hexo-theme-spfk#10]
你好，我想修改一下多说评论那里的样式，因为评论文字的颜色和背景色冲突，看不清楚，但是不知道在哪里替换多说的embed.default.css?9b2a46a0.css这个样式引入，我发现http://luuman.github.io/2016/02/28/MobileRotate/这里是引入多说的embed.dark.css?33f3a5ac.css样式的，打扰了。

**Comment by luuman** [comment]
多说的样式要在，多说后台修改

**Comment by cbfg5210** [comment]
懂了，多谢指教。
