### ISSUE TITLE
Baidu分析硬编码，不支持Github子项目

### ISSUE THREAD

**Issue by Waterstrong** [luuman/hexo-theme-spfk#14]
主题及配色很酷，也想用一下，不过发现两个小问题。其中Baidu Analytics写的Hard Code，另外也不支持Subdirectory，比如xxx.github.io/blog这种情况资源找不到，路径没有加进去。
我修复了这两个问题，可以提Pull Request否？

**Comment by luuman** [comment]
感谢你的支持，当然可以啦，GitHub子项目可以正常展示的，但是可能是页面跳转，如果不是页面跳转的话，可以使用iframe。对百度分析硬编码不太了解？
