### ISSUE TITLE
GitHub 圖片顯示問題

### ISSUE THREAD

**Issue by cwt100** [luuman/hexo-theme-spfk#15]
Hexo deploy 後，
GitHub link 的圖片顯示不出來，只會呈現黑色的樣式。

ps. Local 端測試時，圖片顯示正常。

**Comment by luuman** [comment]
图片展示是可能有链接，应为图片的形式和链接很相似，markdown的原因，貌似不可以访问其他网站的链接图片

**Comment by cwt100** [comment]
@luuman 
左邊側欄，Social info 的 github icon 呈現不出來，只會呈現黑色的樣式

**Comment by cuiyungao** [comment]
我的问题是img src="..."可以正常显示，换到img lazy-src="..."'就不能正常显示了，不知道是哪里出问题了...

**Comment by luuman** [comment]
你要做懒加载，js配置了没！

**Comment by qilanbei** [comment]
github的仓库貌似有大小限制  资源少的话  课一再建一个仓库 用来放置资源 但是如果时间长了  资源太多就不能了 可以将资源传到网上  然后使用线上的地址  --------- 嘿 前端小白

**Comment by qilanbei** [comment]
github的仓库貌似有大小限制  资源少的话  可以再建一个仓库 用来放置资源 但是如果时间长了  资源太多就不能了 可以将资源传到网上  然后使用线上的地址  --------- 嘿 前端小白
