### ISSUE TITLE
顯示繁體中文

### ISSUE THREAD

**Issue by cwt100** [luuman/hexo-theme-spfk#16]
已在 **_config.yml** 中，
設定 **language: zh-tw** ，
但是仍然顯示為簡體中文。

**Comment by luuman** [comment]
默认是简体的，看你的网站已经解决了！

**Comment by luuman** [comment]
试试把json删了

**Comment by cwt100** [comment]
@luuman 
1. icon-house 顯示出來的列表，都是簡體
2.  刪除哪裡的 json ?

**Comment by luuman** [comment]
db.json
