### ISSUE TITLE
代码高亮显示问题

### ISSUE THREAD

**Issue by Abirdcfly** [luuman/hexo-theme-spfk#17]
我的怎么折腾都是
![_001](https://cloud.githubusercontent.com/assets/5100555/14270445/d996747c-fb20-11e5-9c60-c1ffa24cb420.png)

但是您的会在左上角多一个**语言种类**,请问这是怎么办到的呢?

我的代码格式是这样的:
 ``` bash
# 将输入的字符大写转换为小写
echo 'THIS IS SHIYANLOU!' | tr ‘A-Z’ ‘a-z’
# 将输入的字符中的数字删除
echo 'THIS 123 IS S1HIY5ANLOU!' | tr -d ‘0-9’
```

**Comment by luuman** [comment]
http://luuman.github.io/2015/12/27/Hexo-plug/#highlight-js

修改了配置

**Comment by Abirdcfly** [comment]
感谢,我之前一直没往这方面想,一直以为是哪里配置出了问题.
