### ISSUE TITLE
StackOverflow不显示

### ISSUE THREAD

**Issue by codefalse** [luuman/hexo-theme-spfk#18]
在配置文件中设置StackOverflow,之后在页面中有stackoverflow出现，就是不显示图标！

**Comment by luuman** [comment]
我没有添加StackOverflow，可以自行添加，修改样式！

**Comment by codefalse** [comment]
还有个我问题，我看你的样例上边都是显示的文章标题列表，为啥我的就基本上显示了全部呢，而不是列表呢？需要在哪里配置吗？

**Comment by luuman** [comment]
这个你应该看我的文档，md文档格式，more  首页摘要  http://luuman.github.io/2016/01/15/Hexo-Theme/
