### ISSUE TITLE
打开后卡在了动画但不进入首页怎么办？

### ISSUE THREAD

**Issue by jellycookie** [luuman/hexo-theme-spfk#2]
是要配置什么才会跳转到/archives吗？

**Comment by luuman** [comment]
F12看看有什么错误的提示，

**Comment by jellycookie** [comment]
<img width="1433" alt="screen shot 2016-01-18 at 12 33 53" src="https://cloud.githubusercontent.com/assets/3883409/12383362/2a8c3430-bde0-11e5-9bbf-bd19812762ca.png">

**Comment by jellycookie** [comment]
你的报错还不少于，这个问题我也在找，好像是几个按钮的问题，我的这个加载是网页加载完成了，才会进入页面@any suggestions?

**Comment by liuhao2050** [comment]
我也是  卡在动画进不去,报错和上面一样

**Comment by luuman** [comment]
试试这个版本，我把loading去了！https://github.com/luuman/hexo-theme-spfk/tree/Big

**Comment by liuhao2050** [comment]
赞！我刚才也从你的blog中把这几个文件加进去了 @luuman 
这个问题应该可以close了
