### ISSUE TITLE
圆片显示问题

### ISSUE THREAD

**Issue by MuDeBin** [luuman/hexo-theme-spfk#20]
**先谢谢你的主题，真的很好看。我不知道是不是bug还是我自己改错了。圆片在首页的时候可以正常显示，到了阅读文章的页面时，就只显示了一个带颜色的圆，没有head.jpg图片显示。望您可以抽时间帮忙解决下，再次感谢！**

**Comment by luuman** [comment]
主题的# Link to your avatar | 填写头像地址
avatar: /img/head.jpg

# Small icon of Your site | 站点小图标地址

favicon: /img/favicon.png

**Comment by MuDeBin** [comment]
多谢！我的路径哪里少了 （/）/img/head.jpg。
另外，我想再问下那个菜单里面的博客首页是怎么做的？用到jquery？？还是自己写出来的？谢谢解答！
