### ISSUE TITLE
當螢幕較小時，首頁文章無法正常載入

### ISSUE THREAD

**Issue by LFsWang** [luuman/hexo-theme-spfk#21]
測試環境 Chrome51 dev, Edge

這一個版本明顯，只有兩篇文章，一個是預設的Hello World，一個是我的文章，非常的長，沒有使用 more
https://github.com/LFsWang/lfswang.github.io/tree/4b57f8f1555d9b9380b62360ec47a35377ac8c3f

1366x768顯示效果
![image](https://cloud.githubusercontent.com/assets/7088579/14589078/f33c67e8-050b-11e6-989b-51b759c7b97a.png)

1680x1050效果
![image](https://cloud.githubusercontent.com/assets/7088579/14589079/fd5a3322-050b-11e6-9a29-918f385cf723.png)

加了more
1366x768顯示效果
![image](https://cloud.githubusercontent.com/assets/7088579/14589076/e8aa2180-050b-11e6-9888-5c02b4677cf5.png)

1680x1050效果
![image](https://cloud.githubusercontent.com/assets/7088579/14589075/d754854c-050b-11e6-9f9e-02b05800bef9.png)

發現當螢幕尺寸較小時，首頁可顯示的文章會被判別為未顯示，結果就被拿掉了，但是其實是應該要顯示出來的。

1366x768是我寫code的筆電，是1680x1050是我demo用的，我push後才發現這一件事

其實還有一些細瑣的issue我先修掉了，不過這個我解不出來

**Comment by luuman** [comment]
文章的简介吗，短小精炼，如果你把动态效果关闭了，就没有这个问题了
