### ISSUE TITLE
本地和网页显示不一样

### ISSUE THREAD

**Issue by cyang812** [luuman/hexo-theme-spfk#23]
**你好，非常感谢你的主题。**我是一个新手，今天刚搭建了博客，觉得这个主题很好看。

以下是我的问题：
修改主题文件后，本地端可以显示改变，但是网页端很多效果出不来。

> 包括：
> 1.修改的头像，本地端可以，网页端从开始就只是纯色图片。
> 2.本地端有动画效果，背景也会随机变。网页端从来不变背景，也没有动画效果。

**Comment by luuman** [comment]
看了页面是OK的呀！

**Comment by cyang812** [comment]
感谢你的回复。我换了一个浏览器（firefox）测试，发现确实正常。不知道为何用chrome会不行。

**Comment by luuman** [comment]
吓我一大跳，我的chrome可以呀！
