### ISSUE TITLE
文章默认展开，没有折叠。

### ISSUE THREAD

**Issue by suceser** [luuman/hexo-theme-spfk#32]
文章默认是展开的，没有折叠。

**Comment by weank1984** [comment]
1.在文章中使用  手动进行截断
2.在文章的 front-matter 中添加 description，并提供文章摘录
3.自动形成摘要，在主题配置文件 中添加：
`auto_excerpt:`
`enable: true`
`length: 50`

来源：
http://theme-next.iissnan.com/faqs.html#%E9%A6%96%E9%A1%B5%E6%98%BE%E7%A4%BA%E6%96%87%E7%AB%A0%E6%91%98%E5%BD%95

**Comment by weank1984** [comment]
@guoxiaoxing 
1.在文章中使用  手动进行截断
2.在文章的 front-matter 中添加 description，并提供文章摘录
3.自动形成摘要，在主题配置文件 中添加：
`auto_excerpt:`
`enable: true`
`length: 50`

来源：
http://theme-next.iissnan.com/faqs.html#%E9%A6%96%E9%A1%B5%E6%98%BE%E7%A4%BA%E6%96%87%E7%AB%A0%E6%91%98%E5%BD%95

**Comment by suceser** [comment]
Thanks
