### ISSUE TITLE
最新用户使用主题问题Bug

### ISSUE THREAD

**Issue by luuman** [luuman/hexo-theme-spfk#39]
最近比较忙，都好长时间没有发博文了，最近看看最新用户注册github page都是https://协议了，这个就导致有部分文件无法加载，欢迎大家一起来解决。

**Comment by ghost** [comment]
用七牛云cdn https 加速多说，但头像还是走的http.  已放弃，还是用disqus吧。 表示非常喜欢这款主题，谢谢。

**Comment by luuman** [comment]
其实我也觉得disqus不错，这些插件，你们都不一定要和我一样！
