### ISSUE TITLE
关于不能使用代码高亮的问题

### ISSUE THREAD

**Issue by m9rco** [luuman/hexo-theme-spfk#40]
https://pushaowei.github.io/2016/09/10/swoole_1/
连接在这里 

我的md 写的是对的，而且我换个主题就可以了，官方基础的主题也不行，我换成MOxFIVE的主题代码高亮也解决了

**Comment by luuman** [comment]
我的没有问题呀，看了样式
.article-entry .highlight pre {
    border: none;
    margin: 0;
    padding: 0;
}
把这去掉

**Comment by m9rco** [comment]
好的，谢谢大神，我晚上回去看一下，能不能具体一点这个css在那个位置啊

**Comment by luuman** [comment]
你可以去看看github hexo备份文件里面的语法高亮的部分css

**Comment by m9rco** [comment]
好的，已经解决，感谢解答
