### ISSUE TITLE
链接的样式

### ISSUE THREAD

**Issue by imfht** [luuman/hexo-theme-spfk#50]
看到你的博客里面出现了两种链接
![2016-12-11 4 24 44](https://cloud.githubusercontent.com/assets/15059493/21079091/4db0ff3e-bfc1-11e6-93ef-75f521bb56ba.png)
和
![2016-12-11 4 39 44](https://cloud.githubusercontent.com/assets/15059493/21079092/4de09668-bfc1-11e6-901c-da3879b16328.png)
我用 Markdown 写的链接默认是使用第二种形式，请问怎么写才能召唤出第一种形式的链接？
谢谢

**Comment by luuman** [comment]
# 概况
>1. 为什么选择[GitHub Pages](1)
1、[GitHub Pages](1)有免费的代码托管空间，资料自己管理，保存可靠；
2、学着用 GitHub，享受 GitHub 的便利，上面有很多大牛，眼界会开阔很多；
3、顺便理解 GitHub 工作原理，最好的团队协作流程；
4、GitHub建立私有仓库才会收费，所以会有很多开源代码。
>2. [GitHub Pages](1)是什么
应用GitHub Pages创建属于自己的个人博客，GitHub将提供免费的空间。GitHub提供的域名（用户名+github+io）,在Repository name对应处填写资源名，其需要使用自己的用户名，每个用户名下面只能建立一个，并且资源命名必须符合这样的规则username/username.github.io，之后勾选下面的"Initialize this repository with a README" 。
>3. [hexo](2)出自何人
hexo出自台湾大学生 tommy351 之手，是一个基于Node.js的静态博客程序，其编译上百篇文字只需要几秒。hexo生成的静态网页可以直接放到GitHub Pages，BAE，SAE等平台上。
[0]: https://github.com/ "GitHub"
[1]: https://pages.github.com/ "GitHub Pages"
[2]: http://zespia.tw/hexo/ "hexo"
