### ISSUE TITLE
不是bug，有个问题

### ISSUE THREAD

**Issue by iBotasky** [luuman/hexo-theme-spfk#52]
我看到你的`/about`跟`/tags`下面都有一个`index.html`，请问一下这个是自己生成的吗，还是要自己写啊？我找不到相关的教程。

**Comment by iBotasky** [comment]
@luuman 

还有`/tags`列出来的标签需要一个个写死吗，还是有办法自动获取到然后列出来！

**Comment by luuman** [comment]
title: 分类 & 标签
date: 2015-10-12 21:49:10
fancybox: false
---
有这个md文件，内容自动生成

**Comment by iBotasky** [comment]
OK
