### ISSUE TITLE
请问如何显示社交图标

### ISSUE THREAD

**Issue by yusmile** [luuman/hexo-theme-spfk#53]
您的知乎图标是这么设置的呢？
我用的是NEXT主题，但是在http://www.fontawesome.com.cn/faicons/上没找到相应的图标，应该怎么做呢？

**Comment by luuman** [comment]
图片，还没有更换为icon

**Comment by yusmile** [comment]
我如果用NEXT主题，是否可以像你一样更改社交图标呢？
