### ISSUE TITLE
关于搜索功能的疑问

### ISSUE THREAD

**Issue by chineselzh** [luuman/hexo-theme-spfk#58]
这个主题是我发现的`最最最最精美`的主题了，没有之一，感谢大大的作品！
唯一的缺憾就是目前搜索功能不能用，希望大大能够添加**搜索功能**谢谢！
另外：能否增加`置顶`的功能，目前发现只有[freemind主题](https://github.com/wzpan/hexo-theme-freemind)支持`置顶`功能，希望大大考虑，谢谢！

**Comment by luuman** [comment]
准备重新写，暂时不会更新了，可以自行尝试！
