### ISSUE TITLE
评论系统的问题

### ISSUE THREAD

**Issue by huFly** [luuman/hexo-theme-spfk#62]
因为多说现在说要关停服务,我就启用了友言,也设置了友言的id,但部署服务器上仍然显示不出友言,不知还需要什么设置?...

**Comment by huFly** [comment]
经调试网页发现 有个http://jsapi.uyan.cc/ 的GET请求报 502错误. (可能是友言服务器问题??)不知博主有没有开启友言成功?

**Comment by luuman** [comment]
对评论系统有点失望，转用gitment了，哈哈

**Comment by eshibudaoweng** [comment]
@luuman 请教一下作者在哪里添加的gitment评论系统？主题的版本有更新吗？谢谢。

**Comment by luuman** [comment]
暂时没有修改进去！

**Comment by luuman** [comment]
done!
