### ISSUE TITLE
评论内容字体颜色和背景颜色一样

### ISSUE THREAD

**Issue by yuchuangu85** [luuman/hexo-theme-spfk#68]
评论内容字体颜色和背景颜色一样，请问在哪里修改

**Comment by luuman** [comment]
请上传图片

**Comment by yuchuangu85** [comment]
<img width="956" alt="screen shot 2017-09-23 at 10 36 25" src="https://user-images.githubusercontent.com/7369323/30769445-1618886a-a04b-11e7-8451-aa7017d5a41e.png">
<img width="959" alt="screen shot 2017-09-23 at 10 36 10" src="https://user-images.githubusercontent.com/7369323/30769448-18811c0c-a04b-11e7-9d32-641bced0555a.png">

**Comment by luuman** [comment]
我在最新的主题里加了gitment的主题

**Comment by yuchuangu85** [comment]
@luuman 新的主题在哪里，能发个链接吗，谢谢。
