### ISSUE TITLE
关于语法高亮问题

### ISSUE THREAD

**Issue by LiVincent-Zhang** [luuman/hexo-theme-spfk#7]
用来高亮objc时效果很差，我用的是 ```objc，请问这样对么？

**Comment by luuman** [comment]
因为使用的markdown语法http://luuman.github.io/2015/12/24/markdown/
，高亮效果是自己，自行修改的，highlight.styl

highlight.http://luuman.github.io/2015/12/27/Hexo-plug/#highlight-js
