### ISSUE TITLE
gitment配置

### ISSUE THREAD

**Issue by giscrazier** [luuman/hexo-theme-spfk#72]
你好，非常感谢您提供这么漂亮的主题。在使用的过程中，我的gitment配置不了，不知道是哪里的问题，请赐教：
下面是我在themes/spfk/_config.yml中的配置
![image](https://user-images.githubusercontent.com/15927284/33360909-d13510b0-d510-11e7-8da6-9b29eb735001.png)
在我的博客中：Error: Not Found错误

**Comment by TRHX** [comment]
我也是这种情况

**Comment by DeSireFire** [comment]
把repo 里面 "https://"去掉试试
