### ISSUE TITLE
关于你博客的前端导航是怎么做的？

### ISSUE THREAD

**Issue by zhisheng17** [luuman/hexo-theme-spfk#83]
https://luuman.github.io/FrontEndGuideV2/FrontEndGuide/#/Index

你好，我看你自己博客这里有个前端导航，也是这个博客主题自带的吗？

如果不是的话，那是怎么弄出来？能指导下吗，我也想弄个后端的适合自己日常使用的导航

**Comment by DeSireFire** [comment]
emm，我猜这位作者..基本已经放养这个主题了。
这个主题的repo上的版本是两三年前的。

**Comment by luuman** [comment]
静态页面
