### ISSUE TITLE
spfk主题文件夹为什么提交不到git仓库

### ISSUE THREAD

**Issue by WXiangQian** [luuman/hexo-theme-spfk#85]
spfk主题文件夹为什么提交不到git仓库
![image](https://user-images.githubusercontent.com/33483107/63903171-11afe000-ca3f-11e9-9e3a-c1451613c375.png)
想备份下自己的博客所有文件，然后发现spfk主题提交不到git仓库？
有没有遇到同样的问题？或者有解决方案的大佬。

**Comment by stevenjoezhang** [comment]
用 git submodule
https://git-scm.com/docs/git-submodule
