### ISSUE TITLE
[请教]侧边栏背景自定义

### ISSUE THREAD

**Issue by wuchangfeng** [luuman/hexo-theme-spfk#9]
想自定义一下自己基于Yilia的侧边栏背景，自己在指定目录下添加了指定图片资源，以及修改了主题下的_config.yml文件，请问还要做哪些操作呢？要不要添加Js文件?

Thx

**Comment by luuman** [comment]
https://github.com/luuman/hexo-theme-spfk/blob/master/layout/_partial/background.ejs

**Comment by wuchangfeng** [comment]
您好，我仔细对比了您所说的文件与我使用主题yilia的文件，发现是一样的。但是还是不显示自定义的图片背景，我想是不是设置了默认的背景，没有关闭？还是要做其他一些操作？

麻烦有空的话指导一下，谢谢。

**Comment by luuman** [comment]
css样式也有修改
